name: Dart Analysis
on: [push, pull_request]

jobs:

  package-analysis:

    runs-on: ubuntu-latest

    steps:
      - uses: cedx/setup-dart@v1
      - uses: actions/checkout@v2 # required
      - run: dart tool/env.dart
        env:
          FINESSE_API_TOKEN: ${{ secrets.FINESSE_API_TOKEN }}

      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: flutter pub get
      - uses: axel-op/dart-package-analyzer@stable
        with:
          # Required:
          githubToken: ${{ secrets.GITHUB_TOKEN }}